import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navtop from "./_components/navtop";
import Navbar from "./_components/navbar";
import Footer from "./_components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative h-screen overflow-y-auto`}>
        <div className="relative z-10">
          <Navtop />
          <Navbar />
          <main>{children}</main>
          <Footer />
        </div>
        <video src="videos/background.mp4" className="fixed top-0 left-0 w-full h-full object-cover -z-10" autoPlay loop muted></video>
      </body>
    </html>
  );
}
